{{
    config(materialized='table')
}}

SELECT
  customerid,
  DATE(ORDERDATE) AS order_date,
  DATE(PLANNEDDELIVERYDATE) AS planned_Date,
  DATE(ACTUALDELIVERYDATE) AS delivery_date,
  DATEDIFF('DAY', ACTUALDELIVERYDATE, PLANNEDDELIVERYDATE) AS diff,
  CASE
  WHEN ACTUALDELIVERYDATE = PLANNEDDELIVERYDATE THEN 'ON_TIME'
  WHEN ACTUALDELIVERYDATE < PLANNEDDELIVERYDATE THEN 'EARLY_DELIVERY'
  ELSE 'LATE_DELIVERY'
  END AS Delivery_status,
  ORDERQUANTITY,
  DELIVEREDQUANTITY,
  SHIPPINGCOST,
  REGION,
  DELIVERYSTATUS
FROM
  "SNOWFLAKE_LEARNING_DB"."PUBLIC"."ARMAGEDON_TABLE"